"""Pack qr_damage.py's measured run into a TS module the Remotion reel replays."""
import json

d = json.load(open('projects/r003_qr/qr_data.json'))
N = d['n']
M, F, OW = d['matrix'], d['functional'], d['owner']

flat = lambda g, fn: ''.join(fn(g[r][c]) for r in range(N) for c in range(N))
matrix = flat(M, str)
func = flat(F, str)
owner = flat(OW, lambda v: '.' if v < 0 else str(v))

j = lambda o: json.dumps(o, separators=(',', ':'))
cy, cx = d['blob_centre']

out = f'''// GENERATED by projects/r003_qr/emit_ts.py — do not edit by hand.
//
// Every value here is measured output from qr_damage.py, which encodes a real
// QR (version 5, error level H), rebuilds the module -> codeword -> Reed-Solomon
// block mapping from the spec, proves it by reconstructing the payload byte for
// byte, then damages the code and asks OpenCV — not us — whether it still reads.

export const N = {N};
export const PAYLOAD = {j(d['payload'])};

/** Row-major, one char per module. '1' = dark. */
export const MATRIX = {j(matrix)};
/** '1' = functional (finder, timing, alignment, format) — carries no data. */
export const FUNC = {j(func)};
/** Which of the 4 Reed-Solomon blocks owns each module; '.' = functional. */
export const OWNER = {j(owner)};

/** The stain is a growing disc, so the reel recomputes it rather than storing 31 masks. */
export const BLOB_CY = {cy};
export const BLOB_CX = {cx};

/** Speckle damage accumulates along one fixed permutation — take the first n. */
export const SPECKLE_ORDER: [number, number][] = {j(d['speckle_order'])};

export type Step = {{ pct: number; modules: number; ok: boolean }};
export const BLOB: Step[] = {j(d['blob'])};
export const SPECKLE: Step[] = {j(d['speckle'])};

export const STATS = {{
  version: {d['version']},
  ecl: {j(d['ecl'])},
  dataModules: {d['data_modules']},
  functionalModules: {d['functional_modules']},
  blocks: {d['blocks']},
  ecPerBlock: {d['ec_per_block']},
  correctsPerBlock: 11,
  blockTotal: 33,
  blobMax: {d['blob_max']},
  // blobMax is a share of the DATA-carrying area (1079 of 1369 modules). What a
  // viewer actually sees covered is the share of the WHOLE square — so that is
  // the number the reel puts on screen, computed here rather than by hand.
  blobMaxOfSquare: {round(d['data_modules'] * d['blob_max'] / 100 / (d['n'] ** 2) * 100)},
  speckleMaxOfSquare: {round(d['data_modules'] * d['speckle_max'] / 100 / (d['n'] ** 2) * 100)},
  speckleMax: {d['speckle_max']},
  cornerModules: {d['corner_modules']},
  cornerPct: 0.7,
  cornerOk: {str(d['corner_ok']).lower()},
}};
'''
open('remotion/src/reels/data/qr.ts', 'w').write(out)
print(f'wrote remotion/src/reels/data/qr.ts  ({len(out):,} chars)')
print(f'  stain survives {d["blob_max"]}%   speckle {d["speckle_max"]}%   '
      f'corner {d["corner_modules"]} modules -> {"reads" if d["corner_ok"] else "dead"}')
