#!/usr/bin/env python3
"""
generate_images.py — still-image generation for The Engineering Atlas (Gemini "nano banana").

Reads the LEAN storyboard.json, composes each scene's full prompt via prompt_builder
(style_card.txt prefix + scene_recipes + accent_hex + composition), and writes
images/scene_NN.png. That's it — this script only makes the stills.

Animation is NOT done here. Clips are generated by Claude through the connected
**Kling MCP** (image_to_video), because MCP tools are agent-invoked, not callable from
Python. See the `the-engineering-atlas-video` skill → Phase 3 for that procedure, and
`python prompt_builder.py <sb> --anim-jobs` to prep the per-scene animation requests.

Setup
-----
    pip install google-genai
    cp .env.example .env    # fill GEMINI_API_KEY (Google AI Studio)

Usage (from repo root)
----------------------
    SB=projects/001_chand_baori/storyboard.json
    python generate_images.py --storyboard $SB --scenes 1   # the anchor; eyeball it
    python generate_images.py --storyboard $SB              # the rest, referencing scene 1
    python generate_images.py --storyboard $SB --dry-run    # plan + one sample composed prompt
"""

import argparse, base64, json, os
from pathlib import Path

from prompt_builder import context_from, compose_image_prompt

SCRIPT_DIR = Path(__file__).resolve().parent
IMAGE_MODEL_DEFAULT = "gemini-3.1-flash-image"          # Nano Banana 2


def load_dotenv(*candidates):
    for p in candidates:
        p = Path(p)
        if p.is_file():
            for line in p.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


def parse_scene_selection(spec, n):
    """'1,3,5-9' -> set of 1-based indices; None/'' -> all."""
    if not spec:
        return set(range(1, n + 1))
    out = set()
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if "-" in chunk:
            a, b = chunk.split("-"); out.update(range(int(a), int(b) + 1))
        elif chunk:
            out.add(int(chunk))
    return {i for i in out if 1 <= i <= n}


def generate_image(prompt, out_path, ref_paths=(), model=IMAGE_MODEL_DEFAULT):
    """Gemini image generation via google-genai `models.generate_content`. ref_paths, in
    order: the style anchor (locks the LOOK across scenes), then optionally a real
    reference photo (locks the GEOMETRY — the prompt's facts clause tells the model
    which image plays which role)."""
    from google import genai            # lazy import so --dry-run/--help need no deps
    from google.genai import types
    client = genai.Client()             # reads GEMINI_API_KEY from env
    parts = [types.Part.from_text(text=prompt)]
    for p in (Path(x) for x in ref_paths if x and Path(x).is_file()):
        mime = "image/jpeg" if p.suffix.lower() in (".jpg", ".jpeg") else "image/png"
        parts.append(types.Part.from_bytes(data=p.read_bytes(), mime_type=mime))
    resp = client.models.generate_content(model=model, contents=parts)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    for cand in (resp.candidates or []):
        for part in (getattr(cand.content, "parts", None) or []):
            data = getattr(getattr(part, "inline_data", None), "data", None)
            if data:
                out_path.write_bytes(base64.b64decode(data) if isinstance(data, str) else data)
                return
    raise RuntimeError("no image returned (check model output modality / safety block)")


def main():
    ap = argparse.ArgumentParser(description="Generate still images from a lean storyboard.json (Gemini nano banana)")
    ap.add_argument("--storyboard", default="storyboard.json")
    ap.add_argument("--style-card", default=str(SCRIPT_DIR / "style_card.txt"))
    ap.add_argument("--scenes", default="", help='e.g. "1,3,5-9" (default: all)')
    ap.add_argument("--ref", default="", help="reference image for consistency (default: auto scene 01)")
    ap.add_argument("--model", default=IMAGE_MODEL_DEFAULT, help="image model (e.g. gemini-3-pro-image for hero frames)")
    ap.add_argument("--force", action="store_true", help="regenerate even if the output exists")
    ap.add_argument("--dry-run", action="store_true", help="print the plan + one sample composed prompt; no API calls")
    args = ap.parse_args()

    sb_path = Path(args.storyboard).resolve()
    root = sb_path.parent
    load_dotenv(SCRIPT_DIR / ".env", root / ".env", Path(".env"))
    sb = json.loads(sb_path.read_text())
    scenes = sb["scenes"]
    sel = parse_scene_selection(args.scenes, len(scenes))
    ctx = context_from(sb, args.style_card)   # accent_hex + recipes (from storyboard) + style prefix

    manifest_path = root / "assets_manifest.json"
    manifest = json.loads(manifest_path.read_text()) if manifest_path.is_file() else {}

    print(f"== IMAGE PASS ({args.model}) ==")
    sample_shown = False
    for i, s in enumerate(scenes, 1):
        if i not in sel:
            continue
        out = root / s["image"]
        if out.is_file() and not args.force:
            print(f"  scene {i:02d}  skip (exists)"); continue
        ref = args.ref or (str(root / "images/scene_01.png") if i != 1 else "")
        geo = str(root / s["reference_image"]) if s.get("reference_image") else ""
        model = s.get("image_model", args.model)     # per-scene override (hero frames)
        prompt = compose_image_prompt(s, ctx)
        print(f"  scene {i:02d}  image -> {s['image']}"
              + (f"  [ref={Path(ref).name}]" if ref else "  [no ref]")
              + (f"  [geo={Path(geo).name}]" if geo else "")
              + (f"  [{model}]" if model != args.model else ""))
        if args.dry_run:
            if not sample_shown:
                print(f"    ── sample composed prompt (scene {i:02d}) ──\n    {prompt}\n")
                sample_shown = True
            continue
        try:
            generate_image(prompt, out, ref_paths=(ref, geo), model=model)
            manifest.setdefault(f"scene_{i:02d}", {})["image"] = str(out)
        except Exception as e:
            print(f"    ERROR scene {i:02d} image: {e}")

    if not args.dry_run:
        manifest_path.write_text(json.dumps(manifest, indent=2))
        print(f"\nmanifest -> {manifest_path.name}")
    print("done. (animation: run the Kling MCP procedure — skill Phase 3)")


if __name__ == "__main__":
    main()
