"""Turn shazam_data.json into a typed TS module for the Remotion bundle.

The spectrogram is 110 x 126 = 13,860 cells. As JSON numbers that is ~70 KB of
source for tsc to parse; packed one-char-per-cell into a 64-level alphabet it is
13.8 KB and decodes in a single pass. Everything else is small enough to inline.
"""
import json, pathlib

A = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ+/"
d = json.load(open("shazam_data.json"))
g = d["spectrogram"]

packed = "".join(A[min(63, max(0, round(v * 63)))] for row in g["grid"] for v in row)
assert len(packed) == g["nf"] * g["nt"]

def arr(x):
    return json.dumps(x, separators=(",", ":"))

ts = f'''/**
 * r001 — Shazam fingerprinting, precomputed.
 *
 * GENERATED by projects/r001_shazam/emit_ts.py — do not edit by hand.
 * Regenerate:  python3 fingerprint.py && python3 emit_ts.py
 *
 * Every number here is real output from the fingerprinter in fingerprint.py:
 * a genuine STFT, genuine local-maxima peaks, genuine (f1,f2,dt) hashes, and a
 * genuine match whose recovered offset ({d["stats"]["best_offset_seconds"]}s) lands one STFT frame
 * away from where the query was actually cut ({d["meta"]["query_offset_true"]}s).
 */

/** Spectrogram magnitudes packed one char per cell, 64 levels, row-major. */
const PACKED =
  '{packed}';

const A64 = '{A}';

/** grid[f][t] in 0..1, f=0 is the lowest frequency bin. */
export const SPEC: number[][] = (() => {{
  const nf = {g["nf"]}, nt = {g["nt"]};
  const out: number[][] = [];
  for (let f = 0; f < nf; f++) {{
    const row: number[] = [];
    for (let t = 0; t < nt; t++) row.push(A64.indexOf(PACKED[f * nt + t]) / 63);
    out.push(row);
  }}
  return out;
}})();

export const SPEC_NF = {g["nf"]};
export const SPEC_NT = {g["nt"]};

/** Query waveform, normalised -1..1. */
export const WAVE: number[] = {arr(d["waveform"])};

/** Constellation peaks, t and f normalised 0..1. */
export const PEAKS: {{ t: number; f: number; db: number }}[] = {arr(d["peaks"])};

/** Anchor -> target index pairs into PEAKS. */
export const LINKS: [number, number][] = {arr(d["links"])};

/** Matched hash pairs vs the CORRECT track: [database_frame, query_frame]. */
export const HIT: [number, number][] = {arr(d["scatter_hit"])};

/** Matched hash pairs vs a DIFFERENT track — the control. */
export const MISS: [number, number][] = {arr(d["scatter_miss"])};

/** Offset vote histogram: [offset_frames, votes]. */
export const HIST: [number, number][] = {arr(d["histogram"])};

export const STATS = {json.dumps(d["stats"], indent=2)} as const;

export const META = {json.dumps(d["meta"], indent=2)} as const;
'''

out = pathlib.Path("../../remotion/src/reels/data/shazam.ts")
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(ts)
print(f"wrote {out} ({len(ts)/1024:.1f} KB)  packed spectrogram {len(packed)} chars")

# ── spectrogram raster ───────────────────────────────────────────────────────
# A spectrogram is a 2D magnitude field, i.e. genuinely a raster. Emitting it as
# a PNG (rather than ~14k SVG rects) keeps the render fast; the reveal is done in
# the composition by clipping this image, so nothing about it is pre-animated.
import numpy as np
from PIL import Image

W, H = 1008, 644
grid = np.array(d["spectrogram"]["grid"], dtype=np.float32)      # [nf][nt], f asc

# bilinear resize, then flip so low frequencies sit at the BOTTOM of the image
ys = np.linspace(0, grid.shape[0] - 1, H)
xs = np.linspace(0, grid.shape[1] - 1, W)
y0 = np.floor(ys).astype(int); y1 = np.minimum(y0 + 1, grid.shape[0] - 1); wy = (ys - y0)[:, None]
x0 = np.floor(xs).astype(int); x1 = np.minimum(x0 + 1, grid.shape[1] - 1); wx = (xs - x0)[None, :]
top = grid[y0][:, x0] * (1 - wx) + grid[y0][:, x1] * wx
bot = grid[y1][:, x0] * (1 - wx) + grid[y1][:, x1] * wx
img = (top * (1 - wy) + bot * wy)[::-1]

# Perceptual magnitude ramp (viridis family): deep violet -> blue -> teal -> green
# -> yellow. This is the standard scientific spectrogram colouring, which means it is
# simultaneously the most legible option AND far more vibrant than the single-hue blue
# it replaces. The colour is DATA — it encodes dB — not a palette decision.
STOPS = np.array([
    [16, 14, 32],     # 0.00  silence — sits ON the #0B0E14 ground, not over it
    [58, 30, 108],    # 0.20  deep violet
    [40, 118, 152],   # 0.42
    [33, 160, 133],   # 0.62  teal
    [110, 205, 92],   # 0.82  green
    [253, 231, 37],   # 1.00  loudest
], dtype=np.float32)
pos = np.array([0.0, 0.20, 0.42, 0.62, 0.82, 1.0], dtype=np.float32)
flat = np.clip(img, 0, 1).ravel()
rgb = np.stack([np.interp(flat, pos, STOPS[:, k]) for k in range(3)], axis=-1)
rgb = np.clip(rgb.reshape(img.shape[0], img.shape[1], 3), 0, 255).astype(np.uint8)

png = pathlib.Path("../../remotion/public/reels/r001_spectrogram.png")
png.parent.mkdir(parents=True, exist_ok=True)
Image.fromarray(rgb).save(png)
print(f"wrote {png} ({png.stat().st_size/1024:.0f} KB, {W}x{H})")
