/**
 * r002 — Levenshtein autocorrect, precomputed.
 *
 * GENERATED by projects/r002_autocorrect/emit_ts.py — do not edit by hand.
 * Regenerate:  python3 editdistance.py && python3 emit_ts.py
 *
 * Real output from editdistance.py over the real macOS system dictionary
 * (/usr/share/dict/words). The ranking below is whatever 234,454 words
 * returned — `definately` was chosen over `recieve` precisely because the data was
 * clean: for `recieve`, plain edit distance ranks `relieve` (1) above `receive` (2)
 * and gets the answer wrong.
 */

export const TYPO = "definately";
export const TARGET = "definitely";

/** Full DP matrix. GRID[i][j] = edit distance between typo[:i] and target[:j]. */
export const GRID: number[][] = [[0,1,2,3,4,5,6,7,8,9,10],[1,0,1,2,3,4,5,6,7,8,9],[2,1,0,1,2,3,4,5,6,7,8],[3,2,1,0,1,2,3,4,5,6,7],[4,3,2,1,0,1,2,3,4,5,6],[5,4,3,2,1,0,1,2,3,4,5],[6,5,4,3,2,1,1,2,3,4,5],[7,6,5,4,3,2,2,1,2,3,4],[8,7,6,5,4,3,3,2,1,2,3],[9,8,7,6,5,4,4,3,2,1,2],[10,9,8,7,6,5,5,4,3,2,1]];

export const ROWS = 11;
export const COLS = 11;
export const DISTANCE = 1;

/** The optimal alignment, walked back from the corner. This IS the correction. */
export const PATH: { i: number; j: number; v: number; op: string }[] = [{"i":0,"j":0,"v":0,"op":"start"},{"i":1,"j":1,"v":0,"op":"keep"},{"i":2,"j":2,"v":0,"op":"keep"},{"i":3,"j":3,"v":0,"op":"keep"},{"i":4,"j":4,"v":0,"op":"keep"},{"i":5,"j":5,"v":0,"op":"keep"},{"i":6,"j":6,"v":1,"op":"substitute"},{"i":7,"j":7,"v":1,"op":"keep"},{"i":8,"j":8,"v":1,"op":"keep"},{"i":9,"j":9,"v":1,"op":"keep"},{"i":10,"j":10,"v":1,"op":"keep"}];

/** Just the cells where the two words actually diverge. */
export const EDITS: { i: number; j: number; v: number; op: string }[] = [{"i":6,"j":6,"v":1,"op":"substitute"}];

export const CANDIDATES: { word: string; d: number }[] = [{"word":"definitely","d":1},{"word":"definably","d":2},{"word":"delicately","d":2},{"word":"derivately","d":2},{"word":"geminately","d":2}];

export const STATS = {
  "dict_size": 234454,
  "dict_raw_lines": 235976,
  "search_ms": 1035.3,
  "comparisons": 234454,
  "in_dictionary": false
} as const;
