"""Turn autocorrect_data.json into a typed TS module for the Remotion bundle.

Small enough to inline verbatim — no packing needed, unlike r001's 13,860-cell
spectrogram.  Regenerate: python3 editdistance.py && python3 emit_ts.py
"""
import json, pathlib

d = json.load(open("autocorrect_data.json"))
j = lambda x: json.dumps(x, separators=(",", ":"))

ts = f'''/**
 * r002 — Levenshtein autocorrect, precomputed.
 *
 * GENERATED by projects/r002_autocorrect/emit_ts.py — do not edit by hand.
 * Regenerate:  python3 editdistance.py && python3 emit_ts.py
 *
 * Real output from editdistance.py over the real macOS system dictionary
 * (/usr/share/dict/words). The ranking below is whatever {d["dict_size"]:,} words
 * returned — `definately` was chosen over `recieve` precisely because the data was
 * clean: for `recieve`, plain edit distance ranks `relieve` (1) above `receive` (2)
 * and gets the answer wrong.
 */

export const TYPO = {j(d["typo"])};
export const TARGET = {j(d["target"])};

/** Full DP matrix. GRID[i][j] = edit distance between typo[:i] and target[:j]. */
export const GRID: number[][] = {j(d["grid"])};

export const ROWS = {d["rows"]};
export const COLS = {d["cols"]};
export const DISTANCE = {d["distance"]};

/** The optimal alignment, walked back from the corner. This IS the correction. */
export const PATH: {{ i: number; j: number; v: number; op: string }}[] = {j(d["path"])};

/** Just the cells where the two words actually diverge. */
export const EDITS: {{ i: number; j: number; v: number; op: string }}[] = {j(d["edits"])};

export const CANDIDATES: {{ word: string; d: number }}[] = {j(d["candidates"])};

export const STATS = {json.dumps({k: d[k] for k in
    ("dict_size", "dict_raw_lines", "search_ms", "comparisons", "in_dictionary")}, indent=2)} as const;
'''

out = pathlib.Path("../../remotion/src/reels/data/autocorrect.ts")
out.write_text(ts)
print(f"wrote {out} ({len(ts)/1024:.1f} KB)")
